import type { Metadata } from 'next';
import '@/styles/reset.css';

import Header from '@/components/header/header';
import Provider from '@/hooks/ThemeProvider';
import Footer from '@/components/footer/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
